/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prj_form;

import javax.swing.JFrame;

/**
 *
 * @author rolfi.gomes
 */
public class frmINICIAL extends JFrame {

    /**
     * Creates new form frmINICIAL
     */
    public frmINICIAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtRegistro = new javax.swing.JTextField();
        txtDataContratacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 14, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 182, -1, -1));

        txtNome.setText("jTextField1");
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 11, -1, -1));

        txtEmail.setText("jTextField2");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 49, -1, -1));

        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 52, -1, -1));

        jButton2.setText("TROCA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 182, -1, -1));

        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 90, -1, -1));

        jLabel4.setText("Data Contratação:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 147, -1, -1));

        jLabel5.setText("Registro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 121, -1, -1));

        txtCPF.setText("jTextField1");
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 87, -1, -1));

        txtRegistro.setText("jTextField1");
        getContentPane().add(txtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 118, -1, -1));

        txtDataContratacao.setText("jTextField1");
        getContentPane().add(txtDataContratacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 144, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Dados dados=new Dados();
    
    boolean troca=true;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //String aux= this.txtNome.getText();
        //this.txtNome.setText(this.txtEmail.getText());
        //this.txtEmail.setText(aux);
        
        dados.setDados();
        
        String vcli[];
        if(troca==true){
            vcli= dados.getCliente();
            this.setDados(vcli[0],vcli[1], vcli[2], "", "");
        }else{
            vcli= dados.getFuncionario();
            this.setDados(vcli[0],vcli[1],"", vcli[2], vcli[3]);
        }
        troca=!troca;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(this.txtNome.getText());
        System.out.println(this.txtEmail.getText());
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmINICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmINICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmINICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmINICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmINICIAL().setVisible(true);
            }
        });
    }
    
    public void setDados(String nomeaux,
            String emailaux, String cpfaux,
            String registroaux, String dataaux)
    {
        this.txtNome.setText(nomeaux);
        this.txtEmail.setText(emailaux);
        this.txtCPF.setText(cpfaux);
        this.txtRegistro.setText( registroaux );
        this.txtDataContratacao.setText(dataaux);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataContratacao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRegistro;
    // End of variables declaration//GEN-END:variables
}
